import Head from "next/head";
import Header from "../components/Header";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu - build</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <Navbar />
    </div>
  );
}
